server:
 servlet:
    context-path: /desafio-java/api

spring:
   datasource:
      url: jdbc:h2:mem:demodb
      username: sa
      password:
      driveClassName: org.h2.Driver

   h2:
      console:
      enabled: true
      path: /h2-console